language: c

os:
  - linux
  - windows

arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang

install:
    - python -m pip install --upgrade pip
    - python -m pip install --user conan
    - conan config install .conan

    - choco install python --version 3.8
    - python --version
    - python -m pip install --upgrade pip
    - python -m pip install conan
    - conan config install .conan


before_script:
  - mkdir build
  - cd build
  - conan install --build missing ..
  - cmake ..

script:
  - make
  - make test
