language: c

before_install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa

install:
  - sudo apt-get update
  - sudo apt-get install -y libzmq3-dev criterion-dev

before_script:
  - make check

script:
  - make test
