language: c

os:
  - linux
  - windows

compiler:
  - gcc
  - clang

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python pip; fi
  - pip install --user conan
  - conan config install .conan

before_script:
  - mkdir build
  - cd build
  - conan install --build missing ..
  - cmake ..

script:
  - make
  - make test
