&linux_install:
  - python -m pip install --upgrade pip
  - python -m pip install --user conan
  - conan config install .conan

&windows_install:
  - choco install python --version 3.8
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install conan
  - conan config install .conan

language: c

matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
      install:
        <<: linux_install

    - os: linux
      arch: arm64
      compiler:
        - gcc
        - clang
      install:
        <<: linux_install

    - os: windows
      compiler:
        - gcc
        - clang
      install:
        <<: windows_install


before_script:
  - mkdir build
  - cd build
  - conan install --build missing ..
  - cmake ..

script:
  - make
  - make test
