language: c

matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang

    - os: linux
      arch: arm64
      compiler:
        - gcc
        - clang

    - os: windows
      compiler:
        - gcc
        - clang


install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install conan; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then pip install --user conan; fi
  - conan config install .conan

before_script:
  - mkdir build
  - cd build
  - conan install --build missing ..
  - cmake ..

script:
  - make
  - make test
