language: c
sudo: required

os:
  - linux
  - windows

arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang

install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo python -m pip install --upgrade pip; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo python -m pip install --user conan; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then conan config install .conan; fi

    # - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python --version 3.8; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install conan; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then conan config install .conan; fi


before_script:
  - mkdir build
  - cd build
  - conan install --build missing ..
  - cmake ..

script:
  - make
  - make test
