language: c
sudo: required

cache:
  directories:
    - $HOME/.conan/
    - $HOME/.cache/pip

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CC=gcc ARCH=amd64

    - os: linux
      compiler: clang
      env: CC=clang ARCH=amd64

    - os: linux
      arch: arm64
      compiler: gcc
      env: CC=gcc ARCH=arm64

    - os: linux
      arch: arm64
      compiler: clang
      env: CC=clang ARCH=arm64

install:
    - python -m pip install --user conan
    - conan config install .conan

before_script:
  - mkdir build
  - cd build
  - conan install --build missing ..
  - cmake ..

script:
  - make
  - make test
